apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zexbs5low-nodejs 
  janus-idp.io/tekton: zexbs5low-nodejs
  backstage.io/kubernetes-id: zexbs5low-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zexbs5low-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  